spring.application.name=gate-occupancy

spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=INTERNS_DEV;trustServerCertificate=true;

spring.datasource.username=interns
spring.datasource.password=Password123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver